---
- hosts: dev
  roles:
    - precheck
    - apt
    - terraform
    - vagrant
    - git
    - docker
    - pip
    - k8s
    - git
    # - redisloadtesting
    - vim
    - updatedb
    - versions
...
