---
  - name: install apt packages
    apt:
      pkg:
        - apt-transport-https
        - autoconf
        - automake
        - build-essential
        - ca-certificates
        - cmake
        - ctags
        - curl
        - g++
        - gcc
        - git
        - gnupg-agent
        - gnupg2
        - golang
        - htop
        - inotify-tools
        - libevent-dev
        - libpcre3-dev
        - libssl-dev
        - make
        - mlocate
        - mysql-server
        - nodejs
        - npm
        - openjdk-14-jdk
        - pkg-config
        - postgresql-client-12
        - postgresql-12
        - libpq-dev
        - postgresql-server-dev-12
        - python3
        - python3-dev
        - python3-pip
        - redis-server
        - rustc
        - software-properties-common
        - tmux
        - vagrant
        - vim
        - virtualbox
        - wget
        - zlib1g-dev
    become: true
    tags: apt
...
