---
  - name: install apt packages
    apt:
      pkg:
        - apt-transport-https
        - autoconf 
        - automake 
        - build-essential
        - ca-certificates
        - ctags 
        - curl
        - g++
        - gcc
        - git
        - gnupg-agent
        - gnupg2
        - golang
        - htop
        - libevent-dev 
        - libpcre3-dev 
        - libssl-dev
        - make
        - mlocate
        - mysql-server
        - nodejs
        - openjdk-14-jdk
        - pkg-config
        - postgresql-server-dev-all
        - python3
        - python3-dev
        - python3-pip
        - redis-server
        - rustc
        - software-properties-common
        - tmux
        - vim
        - wget
        - zlib1g-dev
    become: true
    tags: apt
...
