---
  - name: install apt packages
    apt:
      pkg:
        - apt-transport-https
        - build-essential
        - ca-certificates
        - curl
        - ctags 
        - g++
        - gcc
        - git
        - gnupg-agent
        - gnupg2
        - make
        - mlocate
        - python3
        - python3-dev
        - python3-pip
        - software-properties-common
        - tmux
        - vim
        - wget
    become: true
    tags: apt
...
