---
- name: create vagrant directory
  file:
    path: "/home/{{ansible_env.USER}}/vagrantsamples/"
    state: directory

- copy:
    src: Vagrantfile
    dest: "/home/{{ansible_env.USER}}/vagrantsamples/Vagrantfile"

- name: vagrant commands
  command: "{{ item }}"
  become: true
  loop:
    - vagrant up
  args:
    chdir: "/home/{{ansible_env.USER}}/vagrantsamples/"
...
