---
  - name: linux kernel 
    git:
      repo: 'https://github.com/torvalds/linux.git'
      dest: "/home/{{ansible_env.USER}}/git/linux"

  - name: create rust lang with rust
    git:
      repo: 'https://github.com/ehsanmok/create-your-own-lang-with-rust'
      dest: "/home/{{ansible_env.USER}}/git/create-your-own-lang-with-rust"

  - name: thesheff17 ca - chromebook ansible
    git:
      repo: 'https://github.com/thesheff17/ca.git'
      dest: "/home/{{ansible_env.USER}}/git/ca"   

  - name: reddit load testing
    git:
      repo: 'https://github.com/RedisLabs/memtier_benchmark.git'
      dest: "/home/{{ansible_env.USER}}/git/memtier_benchmark"    
...