---
  - name: download linux.tar.gz
    get_url:
      url: http://movies.sheffner.com/movies2/linux.tar.gz
      dest: "/home/{{ansible_env.USER}}/git/linux.tar.gz"
    tags: linuxkernel

  - name: extract linux.tar.gz
    command: tar -xf linux.tar.gz
    args:
      chdir: "/home/{{ansible_env.USER}}/git/"
    tags: linuxkernel

  - name: removing linux.tar.gx
    file:
      path: /home/{{ansible_env.USER}}/git/linux.tar.gz
      state: absent
    tags: linuxkernel

  - name: linux kernel
    git:
      repo: 'https://github.com/torvalds/linux.git'
      dest: "/home/{{ansible_env.USER}}/git/linux"
    tags: linuxkernel

  - name: create rust lang with rust
    git:
      repo: 'https://github.com/ehsanmok/create-your-own-lang-with-rust'
      dest: "/home/{{ansible_env.USER}}/git/create-your-own-lang-with-rust"

  - name: thesheff17 ca - chromebook ansible
    git:
      repo: 'https://github.com/thesheff17/ca.git'
      dest: "/home/{{ansible_env.USER}}/git/ca"

  - name: reddit load testing
    git:
      repo: 'https://github.com/RedisLabs/memtier_benchmark.git'
      dest: "/home/{{ansible_env.USER}}/git/memtier_benchmark"

  - name: golangexamples github
    git:
      repo: 'https://github.com/thesheff17/golangexamples.git'
      dest: "/home/{{ansible_env.USER}}/git/golangexamples"

  #- name: ctags for linux kernel
  #  command: ctags -R .
  #  async: 300
  #  poll: 0
  #  args:
  #    chdir: "/home/{{ansible_env.USER}}/git/linux"
...
