---
  - copy:
      src: vimrc
      dest: "/home/{{ansible_env.USER}}/.vimrc"

  - name: cloning nerd tree git repo
    git:
      repo: 'https://github.com/preservim/nerdtree.git'
      dest: "/home/{{ansible_env.USER}}/.vim/pack/vendor/start/nerdtree"

  - name: cloning YouCompleteMe git repo
    git:
      repo: 'https://github.com/ycm-core/YouCompleteMe.git'
      dest: "/home/{{ansible_env.USER}}/.vim/bundle/YouCompleteMe"

  - name: cloning vundle git repo
    git:
      repo: 'https://github.com/VundleVim/Vundle.vim.git'
      dest: "/home/{{ansible_env.USER}}/.vim/bundle/Vundle.vim"

  - name: "install YouCompleteMe"
    command: "{{ item }}"
    loop:
      - git submodule update --init --recursive
      - python3 install.py --all
    args:
      chdir: "/home/{{ansible_env.USER}}/.vim/bundle/YouCompleteMe/"

  - name: Create a directory if it does not exist
    file:
      path: /home/{{ansible_env.USER}}/.vim/colors
      state: directory
      mode: '0755'

  - copy:
      src: wombat256mod.vim
      dest: "/home/{{ansible_env.USER}}/.vim/colors/wombat256mod.vim"

  - name: "install nerd tree"
    command: "{{ item }}"
    loop:
      - vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
...
